### ISSUE TITLE
Force feedback deadzone around the center of the driving wheel

### ISSUE THREAD

**Issue by gmp-capgemini** [nightmode/logitech-g29#23]
Hello,
There seems to be a deadzone around the center of the driving wheel (approximate 'wheel-turn' values between 45 and 55). This generates some issues like the autocenter not really centering as there is always an inaccuracy when approaching the center. And also the user feels the car is too sensitive in this middle section and difficult to maintain in a straight line because of this. 
This is an issue that has been noted by many Logitech G29 users and there seem to be solutions when using it in games like Automobilista 2, Ferrari GT3 or Assetto Corsa, but its in parameters in the game that affect the driving wheel:

https://www.reddit.com/r/AUTOMOBILISTA/comments/s0zxe0/g29_center_feedback_deadzone/
https://www.reddit.com/r/simracing/comments/5hsmj2/should_there_be_a_deadzone_on_g29/

If these games can correct this issue with the driving wheel I speculate there must be a way to do the same with the logitech-g29 API, however I haven't been able to find a way. Is there any?

**Comment by nightmode** [comment]
Interesting. You could certainly send stronger force feedback commands when approaching the center to try to minimize the dead space. Like other commenters mentioned, too much force feedback would send the wheel too far in one direction and then you could get into an oscillating situation where you are not touching the wheel and the wheel is bouncing back and forth a few degrees trying to center itself.

I suspect if you were working on a project with this library and you really wanted to minimize the dead zone, you could, but only through very fine tweaking of force feedback parameters and turn angles of the wheel. Perhaps even with the default auto-centering turned off if you wanted to take full control over those functions. Since there could be differences in motors between different G29 units, I suspect there would not be a magic setting that would work for all wheels, perhaps a setting that got you close to the desired effect for most wheels but I think very fine tweaking would be needed for each individual wheel.

Just my thoughts above, I have not done any experiments and since this library is meant to be used with Node / Javascript, I don't think this library would help out a video game since the video game should probably be the only software talking to the wheel during play.

**Comment by gmp-capgemini** [comment]
I continued researching but couldn't find a perfect solution. However I did find a great solution which I think it's nice in it's simplicity. In the deadzone I just make the car drive straight ('wheel-turn' = 50). This solves a number of issues: the autocenter really works as when you turn and release the driving wheel it won't be affected anymore by the innacuracy of the autocenter, as it will stay in a value inside the deadzone, thus setting 'wheel-turn' to 50. Also it feels more like a real vehicle where the driving wheel it's less sensible in the middle and it gets more sensible the more you turn.
