### ISSUE TITLE
Interested in adding G923?

### ISSUE THREAD

**Issue by Canees** [nightmode/logitech-g29#27]
Many thanks to the author for his efforts. If I want to increase support for G923, can I simply modify the findwheel function? (Tests will be conducted in the future). I wrote a little bit with node-hid, although I got the relevant data, but the link and disconnect is always imperfect, I can help with the relevant debugging if needed.

```
  const HID = require('node-hid');
  let data = null
  try {
      const devices = HID.devices();
      const logitech = devices.filter(el => el.manufacturer === 'Logitech' && el.product.includes('G923'));
      if(!logitech.length) throw 'Please link to G923'
      data = new HID.HID(logitech[0].vendorId, logitech[0].productId);
      data.on('data', (db) => {
          if (process.connected) { process.send(db) } else {
              throw { type: 'err', text: 'process.connected=false' }
          }
      })
  } catch (error) {
      if (data) data.close()
      process.send({ type: 'err', text: error + '' })
  }
```

**Comment by nightmode** [comment]
This library is only for the G29 but I would encourage you or anyone else to use this library as a basis for supporting other Logitech wheel systems.

If I was going to use this library as a basis to create a new library for another wheel system I would probably do something like the following.

- Use the node-hid list feature to see if the wheel system always shows up with one or more text strings or codes. Ideally checking on a Windows, Mac, and Linux machine. Then have a simple IF statement to look for one or more strings to detect the wheels system across various operating systems.
- Figure out if the current init routine that causes the wheel to calibrate itself works and if it does NOT, go looking in simulation racing forums for the magic code that makes the wheel calibrate itself. Sim racing forums is where I found the previous calibration routine and some other unique info.
- Once the wheel can be found, calibrated, and communicated with, have a live feed of data and press buttons, turn the wheel, step on the gas pedal, and go through each and every thing the wheel can do in order to map out what data equals what was done. This is incredibly tedious but it must be done to translate human-unfriendly int or even bit level number changes into actual events to like shift down, shift up, gas 50, brake 100, etc...

If the above looks like a micro boat load of work... it is. That is why I wish whomever undertakes such work the best of luck. ^_^
