### ISSUE TITLE
 Inquiry About Compatibility with Logitech G923

### ISSUE THREAD

**Issue by Tranquil521** [nightmode/logitech-g29#28]
Hi,

I’ve been using your npm package for the Logitech G29, and it’s working great! I was wondering if this package is compatible with the Logitech G923 as well? If not, are there any plans to support it in the future?

**Comment by nightmode** [comment]
This G29 library is not compatible with the G923, as far as I know. I do not have a G923 to test with so that is my best guess.

This library is just for the G29 although it could be used as the basis to make other libraries for other Logitech wheels or even some kind of multi-wheel library that supports all sorts of devices. That would be pretty cool but not in the cards for me right now.

Thanks for using the G29 library though, it warms my programmer heart to hear it is being used. ^_^
